version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "10:00"
      timezone: "America/Denver"
    commit-message:
      prefix: "actions"
    labels:
      - "dependencies"
    open-pull-requests-limit: 100

  - package-ecosystem: "github-actions"
    directory: "/build-image"
    schedule:
      interval: "monthly"
      time: "10:00"
      timezone: "America/Denver"
    commit-message:
      prefix: "actions"
    labels:
      - "dependencies"
    open-pull-requests-limit: 100

  - package-ecosystem: "github-actions"
    directory: "/git-bump"
    schedule:
      interval: "monthly"
      time: "10:00"
      timezone: "America/Denver"
    commit-message:
      prefix: "actions"
    labels:
      - "dependencies"
    open-pull-requests-limit: 100

  - package-ecosystem: "github-actions"
    directory: "/k8s-job"
    schedule:
      interval: "monthly"
      time: "10:00"
      timezone: "America/Denver"
    commit-message:
      prefix: "actions"
    labels:
      - "dependencies"
    open-pull-requests-limit: 100

  - package-ecosystem: "github-actions"
    directory: "/rules"
    schedule:
      interval: "monthly"
      time: "10:00"
      timezone: "America/Denver"
    commit-message:
      prefix: "actions"
    labels:
      - "dependencies"
    open-pull-requests-limit: 100

  - package-ecosystem: "github-actions"
    directory: "/setup"
    schedule:
      interval: "monthly"
      time: "10:00"
      timezone: "America/Denver"
    commit-message:
      prefix: "actions"
    labels:
      - "dependencies"
    open-pull-requests-limit: 100

  - package-ecosystem: "github-actions"
    directory: "/setup-terraform"
    schedule:
      interval: "monthly"
      time: "10:00"
      timezone: "America/Denver"
    commit-message:
      prefix: "actions"
    labels:
      - "dependencies"
    open-pull-requests-limit: 100

  - package-ecosystem: "github-actions"
    directory: "/terraform-exec"
    schedule:
      interval: "monthly"
      time: "10:00"
      timezone: "America/Denver"
    commit-message:
      prefix: "actions"
    labels:
      - "dependencies"
    open-pull-requests-limit: 100

  - package-ecosystem: "github-actions"
    directory: "/terraform-module"
    schedule:
      interval: "monthly"
      time: "10:00"
      timezone: "America/Denver"
    commit-message:
      prefix: "actions"
    labels:
      - "dependencies"
    open-pull-requests-limit: 100

  - package-ecosystem: "github-actions"
    directory: "/update-cronjob"
    schedule:
      interval: "monthly"
      time: "10:00"
      timezone: "America/Denver"
    commit-message:
      prefix: "actions"
    labels:
      - "dependencies"
    open-pull-requests-limit: 100

  - package-ecosystem: "github-actions"
    directory: "/update-image"
    schedule:
      interval: "monthly"
      time: "10:00"
      timezone: "America/Denver"
    commit-message:
      prefix: "actions"
    labels:
      - "dependencies"
    open-pull-requests-limit: 100

  - package-ecosystem: "github-actions"
    directory: "/update-service"
    schedule:
      interval: "monthly"
      time: "10:00"
      timezone: "America/Denver"
    commit-message:
      prefix: "actions"
    labels:
      - "dependencies"
    open-pull-requests-limit: 100
