name: GHA Experiments
on:
  workflow_dispatch: 
    inputs:
      name:
        description: 'Name of the person to greet'
        required: false
      list_of_things: 
        description: 'List of things'
        required: false
        default: |
          one
          bubbles
          candy float
          knife \n fork
jobs:
  info:
    runs-on: ubuntu-latest
    steps:

    - name: Print GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    
    - name: Print ENV
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: printenv

    - name: N vs Z
      env:
        NAME: ${{ inputs.name }}
      run: |
        
        if [ -z "$NAME" ]; then
          echo "-z is true"
        else
          echo "The name is $NAME"
        fi

        if [ -n "$NAME" ]; then
          echo "-n is true"
        else
          echo "The name is empty"
        fi
        
    - name: Print list of things
      env:
        LIST_OF_THINGS: ${{ inputs.list_of_things }}
      run: |
        
        # loop each item in the list
        while read -r line; do
          echo "Item: $line"
        done <<< "$LIST_OF_THINGS"
        