name: GHA Experiments
on:
  workflow_dispatch: 
    inputs:
      name:
        description: 'Name of the person to greet'
        required: false
      environment:
        description: 'Environment to deploy to'
        required: false
        default: 'dev'
        type: environment
      list_of_things: 
        description: 'List of things'
        required: false
        default: |
          one
          bubbles
          candy float
          knife \n fork
jobs:
  info:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    steps:

    - name: Print GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    
    - name: Print ENV
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: printenv

    - name: N vs Z
      env:
        NAME: ${{ inputs.name }}
      run: |
        
        if [ -z "$NAME" ]; then
          echo "-z is true"
        else
          echo "The name is $NAME"
        fi

        if [ -n "$NAME" ]; then
          echo "-n is true"
        else
          echo "The name is empty"
        fi
        
    - name: Print list of things
      env:
        LIST_OF_THINGS: ${{ inputs.list_of_things }}
      run: |
        
        # loop each item in the space delimited list
        for item in $LIST_OF_THINGS; do
          echo "item: $item"
        done

    - name: The Job
      run: |
        echo '${{ toJSON(env) }}'
        